channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.6
  - pytorch:pytorch==1.12.1
  - pytorch:torchvision==0.13.1
  - ai2thor>=2.5.3
  - attrs==22.1.0
  - attr==0.3.2
  - filelock==3.0.12
  - matplotlib==3.3.3
  - moviepy==1.0.3
  - networkx==2.5
  - numpy
  - numba
  - opencv_python==4.5.1.48
  - Pillow==9.2.0
  - PyYAML==6.0
  - scipy==1.7.3
  - setproctitle==1.2.1
  - setuptools==63.4.1
  - tensorboard==2.10.1
  - tensorboardX==2.5.1
  - tree==0.2.4
  - typing_extensions==4.4.0
  - pip:
    - dm-tree==0.1.7
    - einops==0.5.0
    - ftfy
    - hydra-core==1.3.0
    - mujoco-py>=2.1,<2.2
    - numpy-quaternion
    - omegaconf==2.2.3
    - pyquaternion>=0.9.9
    - python-xlib
    - regex
    - tqdm
    - wandb==0.13.9
    - "--editable=git+https://github.com/openai/CLIP.git@e184f608c5d5e58165682f7c332c3a8b4c1545f2#egg=clip"
    - git+https://github.com/Farama-Foundation/Metaworld.git@master#egg=metaworld
